server:
  port: 8001


#qq邮箱配置
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: gvypvmmgjnwhbceg
    username: 891554093@qq.com

  datasource: #数据库配置
    username: longxin
    password: 20190121!@#
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.54.126:3306/LongXin?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.105.177.77
    password: gaosheng
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mail:
  username: 891554093@qq.com
  #Redis配置



